spring.application.name=multi-database
spring.profiles.active=local
spring.devtools.add-properties=false
server.port = 8080
server.servlet.contextPath = /api/multiDb

#sql db details
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/multidb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jpa.hibernate.ddl-auto=update
spring.datasource.jpa.hibernate.show-sql=true
spring.jpa.database=mysql
spring.datasource.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#mongodb details
spring.data.mongodb.mongodb.uri=mongodb://localhost:27017/multiDb
spring.data.mongodb.mongodb.database=multiDb

logging.level.org.springframework.web=DEBUG

#redis cache
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis



